language: sh

services:
    - docker

before_install:
    - docker pull arm32v7/debian
    - docker images
    - docker build -t my/debian .

script:
    - docker run -itd --name debian-test my/debian
    - python -V
# - docker exec -it debian-test /bin/bash