concurrent = 4 
check_interval = 0 
[session_server] 
  session_timeout = 1800 
[[runners]] 
  name = "us01" 
  request_concurrency = 4 
  url = "https://gitsnps.internal.synopsys.com/" 
  token = "ie-VVMh5RLx9pkVHVY4g" 
  tls-ca-file = "/u/jingru/gitlab-runner/certs/gitsnps.internal.synopsys.com.crt" 
  executor = "shell" 
  environment = [ "GIT_DEPTH=10", "GIT_CLONE_PATH=$CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME" ] 
  [runners.custom_build_dir] 
  [runners.cache] 
    [runners.cache.s3] 
    [runners.cache.gcs]
